name: "Run it:test on Comment"

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: [self-hosted, it_test]

    if: github.event.issue.pull_request && contains(github.event.comment.body, '/it:test')

    steps:

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Run Integration Tests
        run: sbt -J-Xmx40G cleanBuild it:test

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
